### ISSUE TITLE
Regarding the proposed dataset

### ISSUE THREAD

**Issue by thangnn123456** [danhntd/FS-CDIS#1]
According to the CAMO++ website, the dataset hasn't released yet until now. 
Then, how the authors can make their new CAMO-FS dataset? 
Because they mentioned on their paper that " is mainly reconstructed from the CAMO++", "our CAMO-FS comprises 2, 852 images as a result of the inheritance from CAMO++", "For ease of data preparation such as collections and annotations, one of the most common ways is to inherit existing camouflaged datasets and CAMO++ [13] is our selected dataset since it is a high-diversity dataset with a variety of camouflaged object categories", "By gathering more camouflaged animals and combining them with the CAMO++ dataset, we conduct our CAMO-FS dataset", etc.

**Comment by danhntd** [comment]
Thank you for your question! For research purposes, you can directly contact the authors of the CAMO++ [13] dataset to request the data.
